packages:
  - packages/*
  - packages/resolutions-rs/npm/*
  - packages/runtime-rs/npm/*
  - configs/*
  - scripts
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@swc/core"
  - bufferutil
  - bun
  - esbuild
  - fsevents
  - keccak
  - nx
  - secp256k1
  - sharp
  - utf-8-validate
  - wasm-pack
