export type CompilationOutputOption =
	| '*'
	| 'ast'
	| 'abi'
	| 'bytecode'
	| 'deployedBytecode'
	| 'storageLayout'
	| 'gasEstimates'
	| 'methodIdentifiers'
	| 'assembly'
	| 'legacyAssembly'
	| 'ewasm'
	| 'ir'
	| 'irOptimized'
	| 'metadata'
	| 'userdoc'
	| 'devdoc'
